Bug fix: Remove duplicate https being present in response from POST endpoint
PatchesPrime/gurl pull request #3
Opened 2022-08-24 06:40 UTC by Koziad

When making a POST request to the `c/{url}` endpoint and the URL path parameter already contained http/-s in it, then the redirect from shortened URL wouldn't work. Example:

1. POST request being with the following url: `/c/https://www.foo.bar`
2. Response body would return: 
```json
{
    "expires": "2022-08-25T08:37:19.134329099+02:00",
    "uri": "https://https://www.foo.bar", // <-- problem is here
    "key": "B2H7X-0SdYwG",
    "gurl": "http://localhost:9999/b/B2H7X-0SdYwG",
    "token": "291ecd5e-dbe9-41be-b5d2-9e26ff0116fa"
}
```
3. GET request to `http://localhost:9999/b/B2H7X-0SdYwG` will then not work.

2022-08-24 17:08 UTC, PatchesPrime commented on main.go
> +			// Remove http(s) prefix if provided to avoid duplication
Can you think of a way to do it without regexp? :thinking:

2022-08-24 17:10 UTC, PatchesPrime requested changes
Regexp are pretty slow, and this operation could easily be done without it.
Good find, lets try it without a dependency and regexp :+1:

2022-08-24 17:10 UTC, PatchesPrime commented on main.go
> +
Could you do this without regex, though? :thinking:

2022-08-26 17:03 UTC, PatchesPrime requested changes

2022-08-26 17:03 UTC, PatchesPrime commented on main.go
> +				if rune == '/' {
Shouldn't this still not work? It would, in my thinking, trigger on the first slash and include the second in the slice.

2022-08-26 17:06 UTC, Koziad commented on main.go
> +				if rune == '/' {
It would indeed trigger on the first slash, but the redirect works when using the provided `gurl` field from the response body

2022-09-09 03:03 UTC, PatchesPrime approved these changes
Sorry it took so long to get back, but looks good to me.

2022-09-09 03:04 UTC, merged